"use client";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import { Provider } from "react-redux";
import store from "./store/store";

// const manrope = Manrope({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Audiophile",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          {/* <Header /> */}
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
